# Generated by Django 6.0.7 on 2026-08-04 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0003_vgpromocion_vgrecomendacionchef'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpromocion',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de días que el analista definió para la promoción, contados desde fecha_inicio.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
