# Generated by Django 6.0.7 on 2026-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0004_vgpromocion_duracion_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgpromocion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Calculada como fecha_inicio + duracion_dias.', null=True),
        ),
    ]
