# Generated by Django 6.0.7 on 2026-08-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0005_alter_vgpromocion_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpreparacion',
            name='es_adicional',
            field=models.BooleanField(default=False, help_text='Si está activo, el mesero puede ofrecer esta preparación como un extra pagado en cualquier plato.'),
        ),
        migrations.AddField(
            model_name='vgpreparacion',
            name='margen_ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ganancia sobre el costo unitario (ej: 40.00 = 40%). Solo aplica cuando es_adicional=True.', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='VGDetallePedidoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='varagrill.vgdetallepedido')),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_pedidos', to='varagrill.vgpreparacion')),
            ],
            options={
                'verbose_name': 'Adicional de pedido',
                'verbose_name_plural': 'Adicionales de pedido',
                'db_table': 'vg_detalle_pedido_adicional',
            },
        ),
    ]
