# Generated by Django 6.0.7 on 2026-08-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0006_vgpreparacion_es_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgproducto',
            name='receta_vinculada',
            field=models.ForeignKey(blank=True, help_text="Receta del catálogo (VGProducto de categoría 'Recetas') que compone este producto vendible.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_vinculados', to='varagrill.vgproducto'),
        ),
        migrations.AddField(
            model_name='vgproducto',
            name='subreceta_vinculada',
            field=models.ForeignKey(blank=True, help_text='Subreceta que compone este producto vendible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_vinculados', to='varagrill.vgpreparacion'),
        ),
        migrations.AddConstraint(
            model_name='vgproducto',
            constraint=models.CheckConstraint(condition=models.Q(('receta_vinculada__isnull', False), ('subreceta_vinculada__isnull', False), _negated=True), name='producto_vinculo_unico'),
        ),
    ]
