# Generated by Django 6.0.7 on 2026-08-06 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0007_vgproducto_receta_vinculada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGTasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuente', models.CharField(default='BCV', max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'db_table': 'vg_tasas_cambio',
                'ordering': ['-fecha'],
            },
        ),
    ]
