# Generated by Django 6.0.7 on 2026-08-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0008_vgtasacambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgdetallepedido',
            name='grupo_armado',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Agrupa varias líneas de este mismo pedido en un 'plato armado' (ej: carne + guarniciones). Sin agrupar si está vacío.", null=True),
        ),
        migrations.AddField(
            model_name='vgdetallepedido',
            name='peso_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gramos vendidos cuando producto.venta_por_peso está activo (ej: 250.00). Vacío para productos por unidad.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vgproducto',
            name='venta_por_peso',
            field=models.BooleanField(default=False, help_text='Si está activo, precio_venta es el precio por KILOGRAMO y el pedido registra los gramos vendidos en vez de unidades (ej: cortes de carne).'),
        ),
        migrations.AlterField(
            model_name='vgdetallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por unidad, o precio por kilogramo si producto.venta_por_peso.', max_digits=10),
        ),
    ]
