# Generated by Django 6.0.7 on 2026-08-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0009_vgdetallepedido_grupo_armado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='ip_impresora',
            field=models.CharField(blank=True, help_text='IP en la red local de la impresora térmica que imprime las comandas de esta categoría. Vacío = no imprime.', max_length=45),
        ),
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='puerto_impresora',
            field=models.PositiveIntegerField(default=9100, help_text='Puerto TCP de impresión cruda de la impresora (ESC/POS estándar: 9100).'),
        ),
    ]
