# Generated by Django 6.0.7 on 2026-08-13 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0010_vgcategoriaproducto_ip_impresora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGImpresoraCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(blank=True, help_text='IP de la PC de caja donde está compartida la impresora.', max_length=45)),
                ('puerto', models.PositiveIntegerField(default=515, help_text='Puerto del LPD Print Service de Windows (estándar LPD: 515).')),
                ('cola', models.CharField(blank=True, help_text='Nombre exacto de la cola/impresora tal como quedó compartida en Windows.', max_length=100)),
                ('activo', models.BooleanField(default=False, help_text='Si está apagado, cobrar un pedido no intenta imprimir el recibo de caja.')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impresora de caja',
                'verbose_name_plural': 'Impresora de caja',
                'db_table': 'vg_impresora_caja',
            },
        ),
    ]
