# Generated by Django 6.0.7 on 2026-08-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0014_vgmetodopago_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgdetallecompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vgingrediente',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
