# Generated by Django 6.0.7 on 2026-08-24 13:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0015_alter_vgdetallecompra_costo_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGCorrelativoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30, unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Correlativo fiscal',
                'verbose_name_plural': 'Correlativos fiscales',
                'db_table': 'vg_correlativos_fiscales',
            },
        ),
        migrations.CreateModel(
            name='VGDatosFiscalesEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('domicilio_fiscal', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('porcentaje_iva_default', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Datos fiscales del emisor',
                'verbose_name_plural': 'Datos fiscales del emisor',
                'db_table': 'vg_datos_fiscales_emisor',
            },
        ),
        migrations.CreateModel(
            name='VGFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero_factura', models.PositiveIntegerField(unique=True)),
                ('numero_control', models.PositiveIntegerField(unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasa_cambio_referencia', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('abonada_parcial', 'Abonada parcialmente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente_pago', max_length=20)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'vg_facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='VGFacturaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
                'db_table': 'vg_factura_lineas',
            },
        ),
        migrations.CreateModel(
            name='VGOrdenCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Abonada parcialmente'), ('saldada', 'Saldada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Orden de cobro',
                'verbose_name_plural': 'Órdenes de cobro',
                'db_table': 'vg_ordenes_cobro',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VGPreFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('convertida', 'Convertida en factura'), ('anulada', 'Anulada')], default='vigente', max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pre-factura',
                'verbose_name_plural': 'Pre-facturas',
                'db_table': 'vg_prefacturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='VGPreFacturaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Línea de pre-factura',
                'verbose_name_plural': 'Líneas de pre-factura',
                'db_table': 'vg_prefactura_lineas',
            },
        ),
        migrations.AddField(
            model_name='vgcliente',
            name='direccion_fiscal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vgcliente',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Cédula o RIF sin el prefijo (ej: 12345678). Vacío para consumidor final sin datos fiscales.', max_length=20),
        ),
        migrations.AddField(
            model_name='vgcliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('V', 'Cédula (V)'), ('E', 'Cédula de extranjero (E)'), ('J', 'RIF jurídico (J)'), ('G', 'RIF gubernamental (G)'), ('P', 'Pasaporte (P)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vgpago',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='varagrill.vgpedido'),
        ),
        migrations.AddConstraint(
            model_name='vgcliente',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_documento', ''), _negated=True), fields=('tipo_documento', 'numero_documento'), name='uniq_cliente_documento'),
        ),
        migrations.AddField(
            model_name='vgfactura',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgfactura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='varagrill.vgcliente'),
        ),
        migrations.AddField(
            model_name='vgfactura',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgfactura',
            name='pedidos',
            field=models.ManyToManyField(blank=True, related_name='facturas', to='varagrill.vgpedido'),
        ),
        migrations.AddField(
            model_name='vgpago',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='varagrill.vgfactura'),
        ),
        migrations.AddConstraint(
            model_name='vgpago',
            constraint=models.CheckConstraint(condition=models.Q(('pedido__isnull', False), ('factura__isnull', False), _connector='OR'), name='pago_tiene_pedido_o_factura'),
        ),
        migrations.AddField(
            model_name='vgfacturalinea',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='varagrill.vgfactura'),
        ),
        migrations.AddField(
            model_name='vgfacturalinea',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto del menú de origen, cuando la línea viene de un pedido del restaurante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lineas', to='varagrill.vgproducto'),
        ),
        migrations.AddField(
            model_name='vgordencobro',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgordencobro',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgordencobro',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_cobro', to='varagrill.vgfactura'),
        ),
        migrations.AddField(
            model_name='vgordencobro',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_cobro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgprefactura',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgprefactura',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefacturas', to='varagrill.vgcliente'),
        ),
        migrations.AddField(
            model_name='vgprefactura',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vgprefactura',
            name='pedidos',
            field=models.ManyToManyField(blank=True, related_name='prefacturas', to='varagrill.vgpedido'),
        ),
        migrations.AddField(
            model_name='vgfactura',
            name='pre_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='varagrill.vgprefactura'),
        ),
        migrations.AddField(
            model_name='vgprefacturalinea',
            name='prefactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='varagrill.vgprefactura'),
        ),
        migrations.AddField(
            model_name='vgprefacturalinea',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto del menú de origen, cuando la línea viene de un pedido del restaurante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lineas', to='varagrill.vgproducto'),
        ),
    ]
