# Generated by Django 6.0.7 on 2026-08-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0016_vgcorrelativofiscal_vgdatosfiscalesemisor_vgfactura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcompra',
            name='fecha_factura',
            field=models.DateField(blank=True, help_text='Fecha real de la factura del proveedor (puede ser distinta a cuándo se cargó al sistema).', null=True),
        ),
        migrations.AddField(
            model_name='vgcompra',
            name='numero_factura_proveedor',
            field=models.CharField(blank=True, help_text='Número de la factura física del proveedor, para poder rastrear de dónde vino este lote.', max_length=100),
        ),
        migrations.AddField(
            model_name='vgfactura',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='USD', help_text='Moneda en la que se muestra esta factura (tomada del método de pago elegido al emitirla). Los montos siempre se calculan en USD por dentro; esto solo controla en qué moneda se despliega/imprime.', max_length=3),
        ),
        migrations.AddField(
            model_name='vgmovimientoinventario',
            name='compra',
            field=models.ForeignKey(blank=True, help_text='Lote de compra que originó este movimiento (solo entradas ligadas a una compra documentada).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='varagrill.vgcompra'),
        ),
        migrations.AddField(
            model_name='vgprefactura',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='USD', help_text='Moneda en la que se muestra esta cuenta (tomada del método de pago elegido al generarla). Los montos siempre se calculan en USD por dentro; esto solo controla en qué moneda se despliega/imprime.', max_length=3),
        ),
        migrations.AddField(
            model_name='vgprefactura',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
