# Generated by Django 6.0.7 on 2026-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0017_vgcompra_fecha_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgdetallepedido',
            name='costo_unitario_venta',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Costo de receta por unidad (o por kg si venta_por_peso), congelado en el momento del cobro con los costos de ingredientes vigentes ese día. Vacío para pedidos cobrados antes de que este campo existiera — el reporte de margen cae al costo actual para esos casos.', max_digits=12, null=True),
        ),
    ]
