# Generated by Django 6.0.7 on 2026-08-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0018_vgdetallepedido_costo_unitario_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGDetallePedidoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='varagrill.vgdetallepedido')),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_pedidos_opcion', to='varagrill.vgpreparacion')),
            ],
            options={
                'verbose_name': 'Opción elegida de pedido',
                'verbose_name_plural': 'Opciones elegidas de pedido',
                'db_table': 'vg_detalle_pedido_opcion',
            },
        ),
        migrations.CreateModel(
            name='VGGrupoOpcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Acompañante, Término de la carne, Extras.', max_length=100)),
                ('obligatorio', models.BooleanField(default=True, help_text='Si está activo, el mesero debe elegir al menos una opción de este grupo antes de agregar el plato al pedido.')),
                ('seleccion_multiple', models.BooleanField(default=False, help_text='Si está activo, se puede elegir más de una opción del grupo (ej: varios extras). Si no, es una sola (ej: arepas O casabe).')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_opciones', to='varagrill.vgproducto')),
            ],
            options={
                'verbose_name': 'Grupo de opciones de producto',
                'verbose_name_plural': 'Grupos de opciones de producto',
                'db_table': 'vg_grupos_opcion_producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VGOpcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Cuánto se le suma al precio del plato si se elige esta opción (0 si es una sustitución sin costo).', max_digits=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='varagrill.vggrupoopcionproducto')),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_opciones_producto', to='varagrill.vgpreparacion')),
            ],
            options={
                'verbose_name': 'Opción de producto',
                'verbose_name_plural': 'Opciones de producto',
                'db_table': 'vg_opciones_producto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
