# Generated by Django 6.0.7 on 2026-08-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0019_vgdetallepedidoopcion_vggrupoopcionproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgdetallepedidoopcion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_pedidos_opcion', to='varagrill.vgproducto'),
        ),
        migrations.AddField(
            model_name='vggrupoopcionproducto',
            name='categoria_opciones',
            field=models.ForeignKey(blank=True, help_text='Si se define, este grupo es dinámico: el mesero elige entre los productos disponibles de esta categoría en ese momento (ej. Guarniciones), en vez de una lista fija de opciones curadas por el analista. Deja vacío para el modo curado de siempre (usa las opciones de abajo, ligadas a una subreceta específica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_opciones_dinamicos', to='varagrill.vgcategoriaproducto'),
        ),
        migrations.AddField(
            model_name='vggrupoopcionproducto',
            name='maximo_selecciones',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica a grupos dinámicos: tope de cuántas opciones puede elegir el mesero, sin importar cuántas haya disponibles en la categoría. Vacío = sin tope.', null=True),
        ),
        migrations.AlterField(
            model_name='vgdetallepedidoopcion',
            name='preparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_pedidos_opcion', to='varagrill.vgpreparacion'),
        ),
        migrations.AlterField(
            model_name='vggrupoopcionproducto',
            name='obligatorio',
            field=models.BooleanField(default=True, help_text='Si está activo, el mesero debe elegir al menos una opción de este grupo antes de agregar el plato al pedido. Sin efecto en grupos dinámicos (categoria_opciones): esos nunca bloquean, solo avisan.'),
        ),
        migrations.AddConstraint(
            model_name='vgdetallepedidoopcion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('preparacion__isnull', False), ('producto__isnull', True)), models.Q(('preparacion__isnull', True), ('producto__isnull', False)), _connector='OR'), name='detalle_pedido_opcion_un_solo_origen'),
        ),
    ]
