# Generated by Django 6.0.7 on 2026-08-25 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0020_vgdetallepedidoopcion_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcompra',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('abonada_parcial', 'Abonada parcialmente'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='vgcompra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deuda viva con el proveedor por este lote (cuenta por pagar). Baja con cada VGAbonoCompra.', max_digits=10),
        ),
        migrations.CreateModel(
            name='VGAbonoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='varagrill.vgcompra')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_compra', to='varagrill.vgmetodopago')),
            ],
            options={
                'db_table': 'vg_abonos_compra',
            },
        ),
        migrations.CreateModel(
            name='VGCompraBorrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('confirmado', 'Confirmado')], default='abierto', max_length=20)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vg_compras_borrador',
            },
        ),
        migrations.CreateModel(
            name='VGDetalleCompraBorrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, help_text='Lo pagado por esa cantidad de ese ingrediente, según la factura del proveedor.', max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('borrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='varagrill.vgcompraborrador')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra_borrador', to='varagrill.vgingrediente')),
            ],
            options={
                'db_table': 'vg_detalle_compra_borrador',
            },
        ),
    ]
