# Generated by Django 6.0.7 on 2026-08-25 23:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0021_vgcompra_estado_pago_vgcompra_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGCategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'db_table': 'vg_categorias_gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VGGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(help_text='Ej: Factura de luz de agosto, Alquiler de septiembre.', max_length=255)),
                ('proveedor_nombre', models.CharField(blank=True, help_text='A quien se le paga este gasto (opcional).', max_length=150)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonada_parcial', 'Abonado parcialmente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('fecha_gasto', models.DateField(help_text='Fecha real del gasto/factura (puede ser distinta a cuando se registro en el sistema).')),
                ('notas', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='varagrill.vgcategoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'vg_gastos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VGAbonoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos_gasto', to='varagrill.vgmetodopago')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='varagrill.vggasto')),
            ],
            options={
                'db_table': 'vg_abonos_gasto',
            },
        ),
    ]
