# Generated by Django 6.0.7 on 2026-08-27 23:19
#
# El negocio dejo de manejar kilos y litros: de aqui en adelante todo se
# carga en gramos, mililitros o unidad. Esta migracion (1) sube la precision
# de costo_unitario para que un ingrediente barato no se trunque a $0 al
# pasar de "costo por kg" a "costo por gramo", (2) achica las choices de
# unidad_medida/rendimiento_unidad a solo g/ml/unidad, y (3) reescala los
# datos que ya existian en kg/l (x1000 cantidades, /1000 costos por unidad,
# ver varagrill/unit_rescale.py) para que sigan siendo correctos en la nueva
# unidad. Es irreversible a proposito (el reverse_code es un no-op): una vez
# reescalado no queda registro de cuales ingredientes eran kg/l en vez de
# nativamente g/ml, asi que no hay forma segura de deshacerlo automaticamente
# -- el respaldo de base de datos tomado antes de correr esto es el camino de
# reversion real si hiciera falta.

from django.db import migrations, models

from varagrill.unit_rescale import rescale_legacy_units


def rescale_forward(apps, schema_editor):
    rescale_legacy_units(
        VGIngrediente=apps.get_model('varagrill', 'VGIngrediente'),
        VGPreparacion=apps.get_model('varagrill', 'VGPreparacion'),
        VGDetalleCompra=apps.get_model('varagrill', 'VGDetalleCompra'),
        VGDetalleCompraBorrador=apps.get_model('varagrill', 'VGDetalleCompraBorrador'),
        VGRecetaProducto=apps.get_model('varagrill', 'VGRecetaProducto'),
        VGRecetaPreparacion=apps.get_model('varagrill', 'VGRecetaPreparacion'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0024_seed_rol_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgdetallecompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgingrediente',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.RunPython(rescale_forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vgingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vgpreparacion',
            name='rendimiento_unidad',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], max_length=10),
        ),
    ]
