# Generated by Django 6.0.7 on 2026-08-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0025_solo_gramos_ml_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='arma_plato_automatico',
            field=models.BooleanField(default=False, help_text="Si está activo, al mesero agregar un producto de esta categoría al pedido se arma y cierra su propio 'plato' automáticamente, sin pasar por los botones 'Armar plato'/'Terminar'."),
        ),
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='ip_impresora_secundaria',
            field=models.CharField(blank=True, help_text='IP de una segunda impresora que también recibe la comanda de esta categoría, en versión reducida (solo cantidad/peso + nota, sin guarniciones ni adicionales) — ej: Especialidad de la Casa imprimiendo la carne en cocina Y en la parrilla. Vacío = no duplica.', max_length=45),
        ),
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='puerto_impresora_secundaria',
            field=models.PositiveIntegerField(default=9100, help_text='Puerto TCP de la impresora secundaria (ESC/POS estándar: 9100).'),
        ),
    ]
