# Generated by Django 6.0.7 on 2026-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0026_vgcategoriaproducto_arma_plato_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='prioridad_comanda',
            field=models.BooleanField(default=False, help_text="Si está activo, los platos de esta categoría siempre salen primero en la comanda —antes que cualquier otro plato del pedido— y se resaltan con su propio encabezado 'PLATO N - CATEGORÍA', sin importar el orden en que el mesero los agregó ni cuántas líneas tengan. Pensado para entradas, que deben salir antes que el plato principal."),
        ),
    ]
