# Generated by Django 6.0.7 on 2026-08-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0027_vgcategoriaproducto_prioridad_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgingrediente',
            name='contenido_envase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Contenido del envase tal como viene etiquetado, en la misma unidad del ingrediente (g/ml/unidad) — ej. 1000 para una bolsa de 1kg. Junto con 'Peso real' se usa para calcular el costo real por gramo/ml/unidad al confirmar una compra (ver compras_views.admin_compra_borrador_confirmar_view).", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vgingrediente',
            name='peso_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Cuánto de ese envase queda realmente utilizable después de mermas de preparación (pelado, deshuesado, limpieza...). Igual al contenido del envase si no hay pérdida. Si falta este dato o 'Contenido del envase', el costo se calcula con la cantidad comprada tal cual, sin ajustar por merma.", max_digits=10, null=True),
        ),
    ]
