# Generated by Django 6.0.7 on 2026-08-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0028_vgingrediente_contenido_envase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcategoriaproducto',
            name='no_requiere_cocina',
            field=models.BooleanField(default=False, help_text="Si está activo, un pedido donde TODOS los productos sean de categorías marcadas así se registra directamente como 'entregado' — salta cocina y queda listo para cobrar de inmediato, sin imprimir comanda. Pensado para productos empacados para llevar (carnes al vacío, patacones, empanaditas...) que no necesitan preparación. Si el pedido combina esto con un plato normal, ese plato sigue el flujo de cocina de siempre."),
        ),
        migrations.AddField(
            model_name='vgingrediente',
            name='ingrediente_crudo_equivalente',
            field=models.ForeignKey(blank=True, help_text="Si este ingrediente es un producto empacado para reventa (ej. carne al vacío, patacones empacados), a qué ingrediente crudo se le repone el stock al abrir un paquete — ver la acción 'Reponer cocina' en el reporte de ingredientes. Vacío si este ingrediente no es un empacado.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empacados_equivalentes', to='varagrill.vgingrediente'),
        ),
        migrations.AddField(
            model_name='vgingrediente',
            name='rendimiento_ingrediente_crudo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuánto (en la unidad del ingrediente crudo equivalente) rinde CADA paquete de este empacado — ej. 500 si cada paquete de churrasco al vacío trae 500g de carne cruda.', max_digits=10, null=True),
        ),
    ]
