# Generated by Django 6.0.7 on 2026-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0029_vgcategoriaproducto_no_requiere_cocina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgingrediente',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio pagado por el envase/paquete tal como viene etiquetado (el mismo envase de 'Contenido del envase'). Junto con 'Peso real' determina el costo real por gramo/ml/unidad (costo_unitario = precio_compra / peso_real), independiente del contenido nominal del envase — se recalcula automáticamente al crear/editar el ingrediente.", max_digits=12, null=True),
        ),
    ]
