# Generated by Django 6.0.7 on 2026-08-30 17:12

from django.db import migrations, models

# (modelo, campo de fecha a usar para elegir la tasa historica mas cercana)
_MODELOS_A_RELLENAR = [
    ('VGCompra', 'fecha_creacion'),
    ('VGGasto', 'fecha_creacion'),
    ('VGAbonoGasto', 'fecha_pago'),
    ('VGAbonoCompra', 'fecha_pago'),
    ('VGPago', 'fecha_pago'),
]


def backfill_tasa_cambio_referencia(apps, schema_editor):
    """
    Los registros de egresos/pagos creados antes de este campo existir se
    quedarian con tasa_cambio_referencia=NULL para siempre si no se rellenan
    aqui. Para cada uno, se busca la VGTasaCambio mas cercana (la ultima
    conocida antes o en la fecha del registro; si el registro es anterior a
    toda tasa conocida, se usa la mas antigua disponible) en vez de dejarlo
    en NULL, igual que si el sistema hubiera tenido el campo desde el inicio.
    Si no hay ninguna VGTasaCambio en la base (instalacion nueva sin
    historial), no hay nada de donde derivar un valor y los registros
    existentes simplemente quedan sin tasa, igual que un backfill manual.
    """
    VGTasaCambio = apps.get_model('varagrill', 'VGTasaCambio')
    tasas = list(VGTasaCambio.objects.order_by('fecha').values_list('fecha', 'tasa'))
    if not tasas:
        return

    def tasa_para_fecha(fecha):
        anteriores_o_igual = [t for t in tasas if t[0] <= fecha]
        return anteriores_o_igual[-1][1] if anteriores_o_igual else tasas[0][1]

    for nombre_modelo, campo_fecha in _MODELOS_A_RELLENAR:
        Modelo = apps.get_model('varagrill', nombre_modelo)
        pendientes = Modelo.objects.filter(tasa_cambio_referencia__isnull=True)
        for registro in pendientes.iterator():
            fecha_ref = getattr(registro, campo_fecha)
            fecha_dia = fecha_ref.date() if hasattr(fecha_ref, 'date') else fecha_ref
            registro.tasa_cambio_referencia = tasa_para_fecha(fecha_dia)
            registro.save(update_fields=['tasa_cambio_referencia'])


def noop_reverse(apps, schema_editor):
    """No hay nada que deshacer: el AddField reverso ya elimina la columna."""


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0030_vgingrediente_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgabonocompra',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vgabonogasto',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vgcompra',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vggasto',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vgpago',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.RunPython(backfill_tasa_cambio_referencia, noop_reverse),
    ]
