# Generated by Django 6.0.7 on 2026-08-31 23:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0031_add_tasa_cambio_egresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgproducto',
            name='margen_ganancia_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ganancia propio de este producto sobre su costo de receta (ej: 40.00 = 40%). Vacío usa el margen por defecto de VGConfiguracionCosteo.', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='VGConfiguracionCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rendimiento_receta_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje que se suma al costo de CADA receta de producto para compensar mermas de cocina. No aplica a subrecetas.', max_digits=6)),
                ('margen_ganancia_defecto_pct', models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Porcentaje de ganancia sugerido por defecto para productos nuevos que no definen su propio margen.', max_digits=6)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de costeo',
                'verbose_name_plural': 'Configuración de costeo',
                'db_table': 'vg_configuracion_costeo',
            },
        ),
    ]
