# Generated by Django 6.0.7 on 2026-09-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0032_vgproducto_margen_ganancia_pct_vgconfiguracioncosteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgdetallepedidoopcion',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Referencia viva al grupo (además del snapshot grupo_nombre) para poder leer su configuración vigente, ej. gramos_base_racion, al momento de descontar inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_elegidos', to='varagrill.vggrupoopcionproducto'),
        ),
        migrations.AddField(
            model_name='vggrupoopcionproducto',
            name='gramos_base_racion',
            field=models.PositiveIntegerField(blank=True, help_text='Gramos del plato principal que equivalen a 1 ración completa del acompañante elegido (ej: 250 = 1 ración de guarnición por cada 250g de carne pedidos). Solo tiene efecto en productos vendidos por peso; si el peso no cae en un múltiplo exacto, se redondea a la ración más cercana (mínimo 1 ración). Vacío = el acompañante se descuenta a la par del peso del plato, sin lógica de raciones.', null=True),
        ),
    ]
