# Generated by Django 6.0.7 on 2026-09-01 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0033_vgdetallepedidoopcion_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGNotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='USD', max_length=3)),
                ('tasa_cambio_referencia', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrega', to='varagrill.vgcliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrega', to='varagrill.vgmetodopago')),
                ('pedidos', models.ManyToManyField(related_name='notas_entrega', to='varagrill.vgpedido')),
            ],
            options={
                'verbose_name': 'Nota de entrega',
                'verbose_name_plural': 'Notas de entrega',
                'db_table': 'vg_notas_entrega',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
