# Generated by Django 6.0.7 on 2026-09-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0034_vgnotaentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpedido',
            name='fecha_inicio_preparacion',
            field=models.DateTimeField(blank=True, help_text="Momento en que el pedido pasó a 'en_preparacion' (manual o al volver desde 'listo'). Base para el avance automático a 'listo' pasados los minutos configurados — ver _avanzar_pedidos_en_preparacion_vencidos en api_views.py.", null=True),
        ),
    ]
