# Generated by Django 6.0.7 on 2026-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0035_vgpedido_fecha_inicio_preparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpedido',
            name='fecha_listo',
            field=models.DateTimeField(blank=True, help_text="Momento en que el pedido pasó a 'listo' (manual o automático). Base para el avance automático a 'entregado' pasados los minutos configurados — ver _avanzar_pedidos_listos_vencidos en api_views.py.", null=True),
        ),
    ]
