# Generated by Django 6.0.7 on 2026-09-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0036_vgpedido_fecha_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgnotaentrega',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('abonada_parcial', 'Abonada parcialmente'), ('pagada', 'Pagada')], default='pendiente_pago', max_length=20),
        ),
        migrations.AddField(
            model_name='vgnotaentrega',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vgpago',
            name='nota_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='varagrill.vgnotaentrega'),
        ),
    ]
