# Generated by Django 6.0.7 on 2026-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0037_vgnotaentrega_estado_vgnotaentrega_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vgpago',
            name='pago_tiene_pedido_o_factura',
        ),
        migrations.AddConstraint(
            model_name='vgpago',
            constraint=models.CheckConstraint(condition=models.Q(('pedido__isnull', False), ('factura__isnull', False), ('nota_entrega__isnull', False), _connector='OR'), name='pago_tiene_pedido_o_factura_o_nota'),
        ),
    ]
