# Generated by Django 6.0.7 on 2026-09-03 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0038_remove_vgpago_pago_tiene_pedido_o_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGIngresoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('propina', 'Propina'), ('pago_extra', 'Pago extra')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_extra', to='varagrill.vgmetodopago')),
            ],
            options={
                'verbose_name': 'Ingreso extra',
                'verbose_name_plural': 'Ingresos extra',
                'db_table': 'vg_ingresos_extra',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
