# Generated by Django 6.0.7 on 2026-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0039_vgingresoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgingresoextra',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
