# Generated by Django 6.0.7 on 2026-09-04 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0040_vgingresoextra_tasa_cambio_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGCorreccionMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('ingreso_extra', 'Ingreso extra')], max_length=20)),
                ('registro_id', models.PositiveIntegerField(help_text='ID de la VGPago o VGIngresoExtra corregida.')),
                ('motivo', models.CharField(max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('metodo_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_desde', to='varagrill.vgmetodopago')),
                ('metodo_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_hacia', to='varagrill.vgmetodopago')),
            ],
            options={
                'verbose_name': 'Corrección de cuenta',
                'verbose_name_plural': 'Correcciones de cuenta',
                'db_table': 'vg_correcciones_metodo_pago',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
