# Generated by Django 6.0.7 on 2026-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0041_vgcorreccionmetodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgmetodopago',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, help_text="Banco/entidad real donde cae este metodo (ej. 'Banesco'). Varios metodos con el mismo texto se agrupan en Disponibilidad Bancaria. Vacio = no se agrupa.", max_length=80),
        ),
    ]
