# Generated by Django 6.0.7 on 2026-09-05 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0042_vgmetodopago_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgingresoextra',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
