# Generated by Django 6.0.7 on 2026-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0043_alter_vgingresoextra_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgpago',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
