# Generated by Django 6.0.7 on 2026-09-05 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0044_alter_vgpago_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGAjustePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('eliminacion', 'Item eliminado'), ('reduccion', 'Cantidad reducida'), ('movido', 'Movido a otra mesa')], max_length=20)),
                ('producto_nombre', models.CharField(max_length=150)),
                ('cantidad_ajustada', models.PositiveSmallIntegerField()),
                ('mesa_origen', models.PositiveIntegerField(blank=True, null=True)),
                ('mesa_destino', models.PositiveIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='varagrill.vgpedido')),
            ],
            options={
                'verbose_name': 'Ajuste de pedido',
                'verbose_name_plural': 'Ajustes de pedido',
                'db_table': 'vg_ajustes_pedido',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
