# Generated by Django 6.0.7 on 2026-09-06 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0045_vgajustepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('banco_nombre', models.CharField(max_length=80)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], max_length=3)),
                ('saldo_sistema', models.DecimalField(decimal_places=6, max_digits=14)),
                ('saldo_banco', models.DecimalField(decimal_places=6, max_digits=14)),
                ('tasa_cambio_referencia', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(decimal_places=6, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliación bancaria',
                'verbose_name_plural': 'Conciliaciones bancarias',
                'db_table': 'vg_conciliaciones_bancarias',
                'ordering': ['-fecha', 'banco_nombre'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'banco_nombre'), name='uniq_conciliacion_fecha_banco')],
            },
        ),
    ]
