# Generated by Django 6.0.7 on 2026-09-07 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0047_merge_20260906_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgabonogasto',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vggasto',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
