# Generated by Django 6.0.7 on 2026-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0048_alter_vgabonogasto_monto_alter_vggasto_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vggasto',
            name='moneda_origen',
            field=models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='USD', help_text='En que moneda se ingreso el gasto originalmente. Un gasto en VES queda fijo en ese monto de bolivares (se reconstruye siempre con tasa_cambio_referencia, la tasa del dia que se registro); uno en USD se muestra en bolivares con la tasa ACTUAL, para que la deuda en bs se actualice si el BCV cambia mientras sigue pendiente.', max_length=3),
        ),
    ]
