# Generated by Django 6.0.7 on 2026-09-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0049_vggasto_moneda_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgnotaentrega',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento manual en dólares aplicado al cobrar (ej. cliente frecuente, cortesía). 0 = sin descuento, se cobra el total completo de los pedidos.', max_digits=12),
        ),
        migrations.AddField(
            model_name='vgnotaentrega',
            name='descuento_motivo',
            field=models.CharField(blank=True, help_text='Por qué se aplicó el descuento — obligatorio si descuento_monto > 0, para auditoría.', max_length=255),
        ),
    ]
