# Generated by Django 6.0.7 on 2026-09-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0050_vgnotaentrega_descuento_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgabonocompra',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
