# Generated by Django 6.0.7 on 2026-09-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0051_alter_vgabonocompra_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgdetallecompraborrador',
            name='tasa_cambio_referencia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vgdetallecompraborrador',
            name='precio_total',
            field=models.DecimalField(decimal_places=6, help_text='Lo pagado por esa cantidad de ese ingrediente, según la factura del proveedor.', max_digits=14),
        ),
    ]
