# Generated by Django 6.0.7 on 2026-09-14 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0052_vgdetallecompraborrador_tasa_cambio_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGCorreccionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('fecha_gasto_anterior', models.DateField(blank=True, null=True)),
                ('fecha_gasto_nueva', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='varagrill.vggasto')),
                ('metodo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_gasto_desde', to='varagrill.vgmetodopago')),
                ('metodo_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones_gasto_hacia', to='varagrill.vgmetodopago')),
            ],
            options={
                'verbose_name': 'Corrección de gasto',
                'verbose_name_plural': 'Correcciones de gasto',
                'db_table': 'vg_correcciones_gasto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
