# Generated by Django 6.0.7 on 2026-09-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0053_vgcorrecciongasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpedido',
            name='grupo_pedido',
            field=models.ForeignKey(blank=True, help_text='Ancla las rondas de un mismo delivery/para llevar al pedido original, para que Caja las cobre juntas sin depender de que coincida el cliente (nombre/cédula). Vacío = este pedido es su propia ancla (pedido.id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas', to='varagrill.vgpedido'),
        ),
    ]
