# Generated by Django 6.0.7 on 2026-09-21 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0054_vgpedido_grupo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgnotaentrega',
            name='motivo_anulacion',
            field=models.CharField(blank=True, help_text='Por qué se anuló esta nota — se llena al revertirla (ver VGNotaCredito) o al anularla manualmente.', max_length=255),
        ),
        migrations.CreateModel(
            name='VGNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('documento_tipo', models.CharField(choices=[('nota_entrega', 'Nota de entrega'), ('factura', 'Factura')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], max_length=3)),
                ('motivo', models.CharField(choices=[('calidad_plato', 'Calidad del plato'), ('error_mesero', 'Error de mesero / toma de pedido'), ('cliente_cambio', 'Cliente cambió de opinión'), ('error_cobro', 'Error en el cobro'), ('otro', 'Otro')], max_length=20)),
                ('motivo_detalle', models.TextField(blank=True, help_text='Explicación libre de la cajera/mesero sobre lo ocurrido.')),
                ('estado_envio', models.CharField(choices=[('pendiente_envio', 'Pendiente de envío a la API fiscal'), ('confirmada', 'Confirmada por el ente fiscal'), ('error_api', 'Error al enviar a la API fiscal')], default='pendiente_envio', max_length=20)),
                ('uuid_fiscal', models.CharField(blank=True, max_length=100)),
                ('numero_control_referenciado', models.CharField(blank=True, help_text='numero_control de la VGFactura original, o el código de la VGNotaEntrega original.', max_length=50)),
                ('respuesta_api', models.JSONField(blank=True, default=dict)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(help_text='Gerente/Supervisor que re-autenticó la anulación (segundo factor, vía usuario y contraseña).', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='varagrill.vgfactura')),
                ('nota_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='varagrill.vgnotaentrega')),
                ('pedido_nuevo', models.ForeignKey(blank=True, help_text='Primer pedido reabierto en Cobro por esta devolución (ver VGPedido.nota_credito_origen para todos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='varagrill.vgpedido')),
            ],
            options={
                'verbose_name': 'Nota de crédito',
                'verbose_name_plural': 'Notas de crédito',
                'db_table': 'vg_notas_credito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='VGMerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('motivo', models.CharField(choices=[('devolucion_cliente', 'Devolución del cliente'), ('dano_calidad', 'Daño / calidad'), ('otro', 'Otro')], default='devolucion_cliente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='varagrill.vgproducto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='varagrill.vgnotacredito')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'db_table': 'vg_mermas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='vgpago',
            name='anulado_por_nota_credito',
            field=models.ForeignKey(blank=True, help_text="Si no es None, este pago quedó en estado 'anulado' porque una devolución revirtió el documento al que pertenecía — así el cuadre de caja (reportes.py) deja de contarlo automáticamente al filtrar estado='completado', sin perder de qué cuenta/método salió originalmente.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_revertidos', to='varagrill.vgnotacredito'),
        ),
        migrations.AddField(
            model_name='vgpedido',
            name='nota_credito_origen',
            field=models.ForeignKey(blank=True, help_text='Si no es None, este pedido nació de una devolución (ver devoluciones_views.revertir_y_reabrir_pedido): no debe pedir mesa y Cobro debe mostrarlo con una insignia de devolución en vez de un número de mesa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_reabiertos', to='varagrill.vgnotacredito'),
        ),
        migrations.AddConstraint(
            model_name='vgnotacredito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('documento_tipo', 'nota_entrega'), ('factura__isnull', True), ('nota_entrega__isnull', False)), models.Q(('documento_tipo', 'factura'), ('factura__isnull', False), ('nota_entrega__isnull', True)), _connector='OR'), name='nota_credito_un_solo_documento_origen'),
        ),
    ]
