# Generated by Django 6.0.7 on 2026-09-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0055_vgnotaentrega_motivo_anulacion_vgnotacredito_vgmerma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgnotacredito',
            name='tipo_resolucion',
            field=models.CharField(choices=[('reembolso', 'Reembolso — se devuelve el dinero al cliente'), ('canje', 'Canje — el cliente se lleva otro plato del mismo valor'), ('credito_futuro', 'Crédito — queda a favor del cliente para una próxima compra')], default='reembolso', help_text='Qué pasa con el dinero — determina si se descuenta o no del banco/caja (ver docstring de la clase).', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VGCreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], max_length=3)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('usado', 'Usado por completo'), ('vencido', 'Vencido')], default='vigente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='varagrill.vgcliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('nota_credito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credito_generado', to='varagrill.vgnotacredito')),
            ],
            options={
                'verbose_name': 'Crédito de cliente',
                'verbose_name_plural': 'Créditos de cliente',
                'db_table': 'vg_creditos_cliente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
