# Generated by Django 6.0.7 on 2026-09-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0056_vgnotacredito_tipo_resolucion_vgcreditocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vgnotacredito',
            name='estado_envio',
        ),
        migrations.RemoveField(
            model_name='vgnotacredito',
            name='respuesta_api',
        ),
        migrations.RemoveField(
            model_name='vgnotacredito',
            name='uuid_fiscal',
        ),
    ]
