# Generated by Django 6.0.7 on 2026-09-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0057_remove_vgnotacredito_estado_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgnotacredito',
            name='detalle_pedido_origen',
            field=models.ForeignKey(blank=True, help_text="Solo para tipo_resolucion='canje_item': la línea puntual del pedido original que se cambió — el resto de la nota/pedido no se toca.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='varagrill.vgdetallepedido'),
        ),
        migrations.AlterField(
            model_name='vgnotacredito',
            name='tipo_resolucion',
            field=models.CharField(choices=[('reembolso', 'Reembolso — se devuelve el dinero al cliente'), ('canje', 'Canje — el cliente se lleva otro plato del mismo valor'), ('credito_futuro', 'Crédito — queda a favor del cliente para una próxima compra'), ('ajuste_parcial', 'Ajuste parcial — se baja el monto del documento sin anularlo'), ('canje_item', 'Canje de un ítem — solo se cambia un plato, el resto de la nota sigue igual')], help_text='Qué pasa con el dinero — determina si se descuenta o no del banco/caja (ver docstring de la clase).', max_length=20),
        ),
    ]
