# Generated by Django 6.0.7 on 2026-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0058_vgnotacredito_detalle_pedido_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgcreditocliente',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgcreditocliente',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgfactura',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgfactura',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgnotacredito',
            name='monto',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgnotaentrega',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgnotaentrega',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgordencobro',
            name='monto_total',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgordencobro',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
