# Generated by Django 6.0.7 on 2026-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0059_alter_vgcreditocliente_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcompra',
            name='total_bs_factura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
