# Generated by Django 6.0.7 on 2026-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0060_vgcompra_total_bs_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgcompra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Deuda viva con el proveedor por este lote (cuenta por pagar). Baja con cada VGAbonoCompra.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='vgcompra',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
