# Generated by Django 6.0.7 on 2026-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0061_vgcompra_total_saldo_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggasto',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
