# Generated by Django 6.0.7 on 2026-09-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0062_vggasto_saldo_pendiente_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcompra',
            name='moneda_origen',
            field=models.CharField(blank=True, choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='', max_length=3),
        ),
    ]
