# Generated by Django 6.0.7 on 2026-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0063_vgcompra_moneda_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgproducto',
            name='gramos_por_racion',
            field=models.PositiveIntegerField(blank=True, help_text="Solo para productos por peso usados como acompañante de un grupo dinámico con gramos_base_racion (ver VGGrupoOpcionProducto) — cuántos gramos de ESTE producto componen UNA ración (ej: 150 para que 'Yuca sancochada' entregue 150g por cada ración de guarnición, en vez de escalar su receta como si una ración pesara 1kg completo). Vacío = una ración sigue equivaliendo a 1kg (comportamiento de siempre).", null=True),
        ),
    ]
