# Generated by Django 6.0.7 on 2026-09-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0064_vgproducto_gramos_por_racion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vgproducto',
            name='gramos_por_racion',
        ),
    ]
