# Generated by Django 6.0.7 on 2026-09-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0065_remove_vgproducto_gramos_por_racion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vggrupoopcionproducto',
            name='gramos_base_racion',
            field=models.PositiveIntegerField(blank=True, help_text='Gramos del plato principal que equivalen a 1 ración completa del acompañante elegido (ej: 250 = 1 ración de guarnición por cada 250g de carne pedidos). Solo tiene efecto en productos vendidos por peso; si el peso no cae en un múltiplo exacto, se redondea a la ración más cercana (mínimo 1 ración). Vacío = el acompañante se descuenta a la par del peso del plato, sin lógica de raciones. Si el grupo tiene filas en VGRacionAcompanante (tabla de raciones por tamaño), esas filas mandan y este campo se ignora — sirve para cuando las porciones no siguen ninguna fórmula, solo una tabla fija por tamaño (ver esa tabla, reportado 2026-09 con la tarjeta física de referencia).', null=True),
        ),
        migrations.CreateModel(
            name='VGRacionAcompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_tramo', models.PositiveIntegerField(help_text='Peso del plato principal, en gramos, al que aplica esta fila (ej: 250, 500, 750, 1000).')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cuánto de este producto se descuenta en este tramo: gramos si es venta_por_peso, unidades si no.', max_digits=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raciones_por_peso', to='varagrill.vggrupoopcionproducto')),
                ('producto', models.ForeignKey(help_text='El producto acompañante (de la categoría dinámica del grupo) al que aplica esta fila.', on_delete=django.db.models.deletion.CASCADE, related_name='raciones_configuradas', to='varagrill.vgproducto')),
            ],
            options={
                'verbose_name': 'Ración de acompañante por tamaño',
                'verbose_name_plural': 'Raciones de acompañante por tamaño',
                'db_table': 'vg_raciones_acompanante',
                'ordering': ['peso_tramo', 'producto_id'],
                'constraints': [models.UniqueConstraint(fields=('grupo', 'producto', 'peso_tramo'), name='racion_acompanante_unica')],
            },
        ),
    ]
