# Generated by Django 6.0.7 on 2026-09-27 21:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0066_vgracionacompanante'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGAjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('confirmado', 'Confirmado')], default='abierto', max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('notas', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vg_ajustes_inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VGDetalleAjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('suma', 'Suma al stock'), ('resta', 'Resta al stock')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('cantidad_aplicada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aplicado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='varagrill.vgajusteinventario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ajuste_inventario', to='varagrill.vgingrediente')),
            ],
            options={
                'db_table': 'vg_detalle_ajuste_inventario',
            },
        ),
        migrations.CreateModel(
            name='VGCierreInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vg_cierres_inventario',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'mes'), name='unico_cierre_inventario_por_mes')],
            },
        ),
    ]
