# Generated by Django 6.0.7 on 2026-09-29 21:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0067_vgajusteinventario_vgdetalleajusteinventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGTransferenciaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(help_text='Fecha contable del movimiento.')),
                ('moneda_origen', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], max_length=3)),
                ('moneda_destino', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], max_length=3)),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tasa_cambio', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa manual acordada para esta transferencia, solo si hay cruce de moneda — nunca la tasa BCV del día.', max_digits=12, null=True)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('concepto', models.CharField(max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='varagrill.vgmetodopago')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='varagrill.vgmetodopago')),
            ],
            options={
                'verbose_name': 'Transferencia entre cuentas',
                'verbose_name_plural': 'Transferencias entre cuentas',
                'db_table': 'vg_transferencias_cuenta',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
