# Generated by Django 6.0.7 on 2026-09-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0068_vgcompra_moneda_origen_obligatoria'),
        ('varagrill', '0068_vgtransferenciacuenta'),
    ]

    operations = [
    ]
