# Generated by Django 6.0.7 on 2026-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0069_merge_20260929_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgingresoextra',
            name='tipo',
            field=models.CharField(choices=[('propina', 'Propina'), ('pago_extra', 'Pago extra'), ('ingreso_no_facturado', 'Ingreso no facturado')], max_length=20),
        ),
    ]
