# Generated by Django 6.0.7 on 2026-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0070_vgingresoextra_tipo_ingreso_no_facturado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
