# Generated by Django 6.0.7 on 2026-10-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0071_vgcliente_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgpago',
            name='numero_cobro',
            field=models.PositiveIntegerField(blank=True, help_text="Numero correlativo de la NOTA DE COBRO que se imprime al abonar una nota de entrega (serie 'NOTA_COBRO' de VGCorrelativoFiscal). Vacio en pagos de otros origenes o anteriores a este campo.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vgpago',
            name='saldo_posterior',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Saldo pendiente (USD) de la nota de entrega justo DESPUES de este cobro — congelado para que una reimpresion de la nota de cobro muestre lo mismo que el ticket original aunque despues se registren mas abonos.', max_digits=14, null=True),
        ),
    ]
