# Generated by Django 6.0.7 on 2026-10-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0072_vgpago_numero_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgcierrecaja',
            name='conteo_efectivo_realizado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vgcierrecaja',
            name='pos_por_acreditar_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='vgmetodopago',
            name='es_punto_venta',
            field=models.BooleanField(default=False, help_text='Cobros por punto de venta: se agrupan en lotes y suman al saldo cuando el lote se acredita.'),
        ),
        migrations.CreateModel(
            name='VGLotePOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(help_text="Correlativo de la serie 'LOTE_POS'.", unique=True)),
                ('cuenta_bancaria', models.CharField(blank=True, help_text='Snapshot de VGMetodoPago.cuenta_bancaria al abrir el lote.', max_length=80)),
                ('fecha_operacion', models.DateField(help_text='Dia (local) del primer cobro del lote.')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('acreditado', 'Acreditado'), ('anulado', 'Anulado')], default='abierto', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('VES', 'Bolívares')], default='VES', max_length=3)),
                ('monto_bruto_usd', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('monto_bruto_sistema_bs', models.DecimalField(decimal_places=2, default=0, help_text='Suma en Bs de los cobros del lote, cada uno a su tasa congelada.', max_digits=18)),
                ('fecha_abono_real', models.DateField(blank=True, help_text='Dia en que se acredito (sumo al saldo de la cuenta).', null=True)),
                ('fecha_acreditacion', models.DateTimeField(blank=True, null=True)),
                ('acreditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_pos_acreditados', to=settings.AUTH_USER_MODEL)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_pos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pos', to='varagrill.vgmetodopago')),
            ],
            options={
                'verbose_name': 'Lote POS',
                'verbose_name_plural': 'Lotes POS',
                'db_table': 'vg_lotes_pos',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='vgpago',
            name='lote_pos',
            field=models.ForeignKey(blank=True, help_text='Lote de punto de venta al que pertenece este cobro (solo si su metodo_pago es_punto_venta) — ver lotes_pos.asignar_pago_a_lote.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='varagrill.vglotepos'),
        ),
        migrations.AddConstraint(
            model_name='vglotepos',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('metodo_pago',), name='un_lote_abierto_por_metodo'),
        ),
    ]
