# Generated by Django 6.0.7 on 2026-10-04 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0073_punto_venta_lotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VGNotaCreditoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(help_text="Correlativo interno, serie 'NC_COMPRA'.", unique=True)),
                ('numero_documento_proveedor', models.CharField(blank=True, help_text='Numero de la nota de credito que emitio el proveedor (si la trae).', max_length=100)),
                ('fecha', models.DateField(help_text='Fecha de la nota de credito.')),
                ('monto', models.DecimalField(decimal_places=6, max_digits=14)),
                ('monto_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tasa_cambio_referencia', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('anulada', 'Anulada')], default='vigente', max_length=10)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=255)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='varagrill.vgcompra')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de credito de compra',
                'verbose_name_plural': 'Notas de credito de compra',
                'db_table': 'vg_notas_credito_compra',
                'ordering': ['-numero'],
            },
        ),
    ]
