# Generated by Django 6.0.7 on 2026-10-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0074_nota_credito_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgabonocompra',
            name='tasa_manual',
            field=models.BooleanField(default=False),
        ),
    ]
