# Generated by Django 6.0.7 on 2026-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0075_abono_compra_tasa_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgdetallepedido',
            name='margen_produccion_pct_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen de producción (VGConfiguracionCosteo.rendimiento_receta_pct) vigente en el momento del cobro, congelado junto a costo_unitario_venta. Permite separar el costo puro de receta del margen y sumarlo sin contarlo dos veces. Vacío para ventas cobradas antes de que existiera.', max_digits=6, null=True),
        ),
    ]
