# Generated by Django 6.0.7 on 2026-10-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varagrill', '0076_detalle_pedido_margen_produccion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vgprefactura',
            name='tasa_fijada_en',
            field=models.DateTimeField(blank=True, help_text='Cuando se congelo la tasa de esta cuenta. Una pre-factura generada de nuevo para los mismos pedidos dentro de la ventana hereda tasa y hora de la anterior (reimprimir no estira la tasa vieja); la ventana de VENTANA_TASA_PREFACTURA_MIN cuenta desde aqui. Vacio = usa fecha_emision (ver tasa_cuenta.py).', null=True),
        ),
    ]
