"""
Modelos separados en dos archivos segun a que parte del negocio pertenecen:
- restaurant.py: todo lo propio del restaurante (menu, inventario, mesas,
  usuarios, pedidos, promociones...).
- contabilidad.py: metodos de pago y cuadre de caja.
- base.py: VGAuditoria, la base abstracta que usan ambos.

Este __init__ re-exporta todo para que el resto del proyecto siga
haciendo `from .models import X` / `from varagrill.models import X`
exactamente igual que cuando todo vivia en un solo models.py.
"""
from .base import VGAuditoria
from .contabilidad import (
    VGAbonoGasto,
    VGCategoriaGasto,
    VGCierreCaja,
    VGConsignacionCaja,
    VGCorrelativoFiscal,
    VGDatosFiscalesEmisor,
    VGFactura,
    VGFacturaLinea,
    VGGasto,
    VGMetodoPago,
    VGOrdenCobro,
    VGPreFactura,
    VGPreFacturaLinea,
)
from .restaurant import (
    VGAbonoCompra,
    VGCategoriaProducto,
    VGCliente,
    VGCompra,
    VGCompraBorrador,
    VGDetalleCompra,
    VGDetalleCompraBorrador,
    VGDetallePedido,
    VGDetallePedidoAdicional,
    VGDetallePedidoOpcion,
    VGGrupoOpcionProducto,
    VGImpresoraCaja,
    VGIngrediente,
    VGMesa,
    VGMovimientoInventario,
    VGOpcionProducto,
    VGPago,
    VGPedido,
    VGPreparacion,
    VGProducto,
    VGPromocion,
    VGRecetaPreparacion,
    VGRecetaProducto,
    VGRecomendacionChef,
    VGRol,
    VGTasaCambio,
    VGUsuario,
)

__all__ = [
    "VGAbonoCompra",
    "VGAbonoGasto",
    "VGAuditoria",
    "VGCategoriaGasto",
    "VGCategoriaProducto",
    "VGCierreCaja",
    "VGCliente",
    "VGCompra",
    "VGCompraBorrador",
    "VGConsignacionCaja",
    "VGCorrelativoFiscal",
    "VGDatosFiscalesEmisor",
    "VGDetalleCompra",
    "VGDetalleCompraBorrador",
    "VGDetallePedido",
    "VGDetallePedidoAdicional",
    "VGDetallePedidoOpcion",
    "VGFactura",
    "VGFacturaLinea",
    "VGGasto",
    "VGGrupoOpcionProducto",
    "VGImpresoraCaja",
    "VGIngrediente",
    "VGMesa",
    "VGMetodoPago",
    "VGMovimientoInventario",
    "VGOpcionProducto",
    "VGOrdenCobro",
    "VGPago",
    "VGPedido",
    "VGPreFactura",
    "VGPreFacturaLinea",
    "VGPreparacion",
    "VGProducto",
    "VGPromocion",
    "VGRecetaPreparacion",
    "VGRecetaProducto",
    "VGRecomendacionChef",
    "VGRol",
    "VGTasaCambio",
    "VGUsuario",
]
